### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/php-business-ba#1]
- [x] Criar testes para quando for solicitado o PR
- [x] Criar form de cadastro de empresa para quem não domina git

**Comment by gwmoura** [comment]
@paulodealmeida o phpba já tem conta no travis?

**Comment by paulodealmeida** [comment]
Acho que não, cria lá

**Comment by gwmoura** [comment]
@paulodealmeida não tenho acesso para adicionar o repositório no travis

**Comment by gwmoura** [comment]
Ah essa task já foi concluída com o PR #2

**Comment by gwmoura** [comment]
@paulodealmeida a task "Criar testes para quando for solicitado o PR" foi resolvida com PR #4
