### ISSUE TITLE
Dúvida sobre o fluxo

### ISSUE THREAD

**Issue by paulodealmeida** [phpba/php-business-ba#19]
Senhores, estive pensando aqui.

O json será gerado pelo formulário, mas se alguém quiser simplesmente clonar o repo e alterar o json, deverá ser possível.
Eu vejo essa forma de contribuição uma porta aberta para iniciantes.
Não deve ser descartada a alteração do json pelo form, mas deveria ser uma inclusão e não uma geração completa do arquivo.

O que acham?

**Comment by edyonil** [comment]
@paulodealmeida, o código que estou fazendo para ler o form do google forms que @vinaocruz criou vai fazer isso. Ler o código do csv e testar as empresas já cadastradas. Não irei substituir o json e sim complementar. Inclusive o @vinaocruz falou isso comigo. Olha a issue #5

**Comment by paulodealmeida** [comment]
Valeu @edyonil
