### ISSUE TITLE
Criar uma camada de abstração para a consulta dos dados da empresa

### ISSUE THREAD

**Issue by edyonil** [phpba/php-business-ba#8]
A ideia é que nós possamos mudar o acesso dos dados da empresa sem mudar a classe cliente. Hoje vamos ler o csv, mas podemos mudar isso facilmente para banco de dados.

**Comment by gwmoura** [comment]
@edyonil, podemos ter na classe 3 métodos.

1 - getDataFromCsv($csvPath) - lê um arquivo e retorna um array
2 - getDataFromDatabase() - lê de uma base e retorna um array
3 - dataToJson(array $data) - retorna um json

Formato do array:

``` php
[
'website' => 'http://...', 
'empresa' => 'My Company',
...
]
```

O que acha?

**Comment by edyonil** [comment]
Seria mais ou menos isso mesmo. A diferença que pensei em criar duas classes diferentes ao invés de uma classe única com dois métodos. Teríamos uma interface Repository, com assinatura do método getData() com retorno da array. Uma classe RepositoryCsv que vai buscar do google form. Assim cada class que formos implementando fica responsável em implementar sua própria lógica de acesso ao dado, retornando apenas a array, se ligou?

```
[
'website' => 'http://...', 
'empresa' => 'My Company',
...
]
```

**Comment by gwmoura** [comment]
Hummm saquei saquei!!! Bem melhor assim
