### ISSUE TITLE
Adicionar campo ao formulário

### ISSUE THREAD

**Issue by wgbn** [phpba/php-business-ba#9]
Acho que seria interessante adicionar mais um campo no formulário indicando que outra tecnologia/linguagem a empresa usa com e/ou em paralelo ao PHP.
É interessante, pois tenho visto empresas que usam PHP e NodeJS, ou PHP e C# em suas soluções.
Vai ser bom para sabermos pra onde as empresas estão indo, que tendencias tem, etc...

**Comment by paulodealmeida** [comment]
Sugiro o nome do campo other_technologies.
Como um array talvez.

**Comment by paulodealmeida** [comment]
@wgbn vamos aguardar a resolução do #16 para adicionar esse campo.

**Comment by paulodealmeida** [comment]
Criei o campo no json e no form.
